### ISSUE TITLE
letiRmisc vs inSilecoMisc

### ISSUE THREAD

**Issue by amael-ls** [KevCaz/QCBSgraphR#1]
`slidify("docs/index.Rmd")`

Quitting from lines 80-82 (index.Rmd)
Error in library(p, character.only = TRUE) :
  there is no package called 'letiRmisc'

**Comment by KevCaz** [comment]
Thanks @amawl , should be ok now, let me know if it isn't otherwise you can close the issue!

**Comment by amael-ls** [comment]
Problem solved, thanks @KevCaz
